# .streamlit/secrets.toml

[connections.snowpark]
account = "awspartner"
user = "bharaths"
password = "Blippi@1503"
role = "accountadmin"
warehouse = "surebart_wh"
database = "foursquare"
schema = "public"
OPENAI_API_KEY = "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"
